module.exports=
[
{
    name:"Bread Pakoda",

},
{name:'Medu Vada'},
{name:'Masala Dosa'},
{name:'Oats Dosa'},
{name:'Aloo Paratha'},
{name:'Mix veg Paratha'},
{name:'Ragi Roti'},
{name:'Idli'},
{name:'Veg sandwich'},
{name:'Frankie'},
{name:'methi paratha'},
{name:'MT'},
{name:'double Omlette pav'},
{name:'Egg Mayo sandwich'},
{name:'Spicy bread Masala'},
{name:'uttapam'},
{name:'vada sambar'},
{name:'Misal Pav'},
{name:'Khaman Dhokla'},
{name:'Puri Bhaji'},
{name:'Sabudana Vada'},
{name:'Sev Upma'},
{name:'Palak Puri'},
{name:'Rava Idli'},
{name:'Daliya'},
];